name = "searchfastt"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_URL = "https://dear-hermit-50868.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "Aca0AAIncDExNGRiYzIzNmFmZTE0Nzg2ODc4ZTIwNjQyNTM5YjJjOHAxNTA4Njg"