name = "searchfast"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_URL = 'https://fitting-griffon-52566.upstash.io'
UPSTASH_REDIS_REST_TOKEN = 'Ac1WAAIncDFkMzk1Yjc5Yjk1Yjk0ZDBiOTZmMWRiOWQ0MGM2MWQwMXAxNTI1NjY'